/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newclinicprojec.Jpanel;

import java.awt.Component;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.event.EventListenerList;
import javax.swing.table.AbstractTableModel;
import newclinicprojec.controllers.DetailTreatmentJpaController;
import newclinicprojec.controllers.DetailTreatmentTableModel;
import newclinicprojec.controllers.TreatmentJpaController;
import newclinicprojec.controllers.TreatmentTableModel;
import newclinicprojec.entities.DetailTreatment;
import newclinicprojec.entities.Treatment;
/**
 *
 * @author Johm_93
 */
public class addtreatment extends javax.swing.JPanel {

    /**
     * Creates new form addtreatment
     */
    EntityManagerFactory emf;
    TreatmentJpaController treatmentController;
    DetailTreatmentJpaController detailtreatmentController;
    TreatmentTableModel treatmentTablemodel;
    DetailTreatmentTableModel detailTreamentTableModel;

    public addtreatment() {
        initComponents();
    }

    public addtreatment(EntityManagerFactory emf) {
        initComponents();
        this.emf = emf;

        this.treatmentController = new TreatmentJpaController(this.emf);

        List<Treatment> treatment = this.treatmentController.findTreatmentEntities();
        this.treatmentTablemodel = new TreatmentTableModel(treatment);
        tableTreament.setModel(this.treatmentTablemodel);
        this.detailtreatmentController = new DetailTreatmentJpaController(this.emf);
        // List<DetailTreatment> detailtreatment=this.detailtreatmentController.findDetailTreatmentEntities();
        //this.detailTreamentTableModel=new DetailTreatmentTableModel(detailtreatment);
        //tableTreatmentDetail.setModel(detailTreamentTableModel);
        this.setEnableInputForm(this.inputform, false);

        detailTreamentTableModel = new DetailTreatmentTableModel(null);
        tableTreatmentDetail.setModel(detailTreamentTableModel);

    }

    public void setEnableInputForm(boolean b) {

        for (Component c : this.inputform.getComponents()) {
            c.setEnabled(b);
        }
    }

    public void setEnableInputForm(javax.swing.JPanel p, boolean b) {

        for (Component c : p.getComponents()) {
            c.setEnabled(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTreament = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        inputform = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttreatmentid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdoctorid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtteethposition = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttreatment = new javax.swing.JTextField();
        txtcost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTreatmentDetail = new javax.swing.JTable();
        btnsave = new javax.swing.JButton();
        btncancle = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnaddtreat = new javax.swing.JButton();
        btndeletetreat = new javax.swing.JButton();

        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        tableTreament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Customer Id", "Date", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTreament);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnnew)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnew)
                .addGap(0, 571, Short.MAX_VALUE))
        );

        jLabel1.setText("Add Treatment&Payment Data");

        jLabel2.setText("Treatment ID");

        jLabel3.setText("Customer ID");

        jLabel5.setText("Doctor ID");

        jLabel6.setText("Teeth Position");

        jLabel7.setText("Treatment");

        jLabel8.setText("Cost");

        tableTreatmentDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Teeth Position", "Treatment", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTreatmentDetail);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancle.setText("Cancle");
        btncancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancleActionPerformed(evt);
            }
        });

        jLabel9.setText("Date");

        btnaddtreat.setText("Add");
        btnaddtreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtreatActionPerformed(evt);
            }
        });

        btndeletetreat.setText("Delete");
        btndeletetreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletetreatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputformLayout = new javax.swing.GroupLayout(inputform);
        inputform.setLayout(inputformLayout);
        inputformLayout.setHorizontalGroup(
            inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputformLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addGap(18, 18, 18)
                .addComponent(btncancle)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputformLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(inputformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaddtreat)
                    .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputformLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcost, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txttreatmentid)
                            .addComponent(txtcustomerid)
                            .addComponent(txtdoctorid)
                            .addComponent(txtteethposition)
                            .addComponent(txttreatment)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputformLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndeletetreat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputformLayout.setVerticalGroup(
            inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputformLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttreatmentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtteethposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddtreat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeletetreat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btncancle))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleActionPerformed
        // TODO add your handling code here:
        setFielNull();
        setNullFiel();
       detailTreamentTableModel.getDetailtreatment().clear();
        this.setEnableInputForm(inputform, false);
       detailTreamentTableModel.fireTableDataChanged();
    }//GEN-LAST:event_btncancleActionPerformed


    private void btnaddtreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtreatActionPerformed
        // TODO add your handling code here:
//        this.detailtreatmentController=new DetailTreatmentJpaController(this.emf);
//        List<DetailTreatment> detailtreatment=this.detailtreatmentController.findDetailTreatmentEntities();
//        this.detailTreamentTableModel=new DetailTreatmentTableModel(detailtreatment);
//        tableTreatmentDetail.setModel(detailTreamentTableModel);
//        //String treatid=txttreatmentid.getText();
//        //int treatmentid=Integer.parseInt(treatid);
//         //currenDetailTreatment.setTreatmentId(treatmentid);
//         int teethpos=Integer.parseInt(txtteethposition.getText());
//         currenDetailTreatment.setTeethPosition(teethpos);
//         currenDetailTreatment.setTreat(txttreatment.getText());
//         Double cost=Double.parseDouble(txtcost.getText());
//         currenDetailTreatment.setCost(cost);
//         if(currenDetailTreatment.getId() != null&&currenDetailTreatment.getId()!=0){
//            try {
//                detailtreatmentController.edit(currenDetailTreatment);
//                detailTreamentTableModel.fireTableDataChanged();
//            } catch (Exception ex) {
//                Logger.getLogger(customerdata.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }else {
//            detailtreatmentController.create(currenDetailTreatment);
//           // int ii=1;
//           detailTreamentTableModel.detailTreatment.add(currenDetailTreatment);
//            detailTreamentTableModel.fireTableDataChanged();
//            txtteethposition.setText("");
//            txtcost.setText("");
//            txttreatment.setText("");
//    }

        DetailTreatment newDT = new DetailTreatment();
        newDT.setCost(new Double(txtcost.getText()));
        newDT.setTeethPosition(new Integer(txtteethposition.getText()));
        newDT.setTreat(txttreatment.getText());
        detailTreamentTableModel.getDetailtreatment().add(newDT);
        detailTreamentTableModel.fireTableDataChanged();
        setNullFiel();

    }//GEN-LAST:event_btnaddtreatActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        int treatmentid = Integer.parseInt(txttreatmentid.getText());
        setTreatment.setTreatmentId(treatmentid);
        int customid = Integer.parseInt(txtcustomerid.getText());
        setTreatment.setCustomerId(customid);

        setTreatment.setDoctorId(Integer.parseInt(txtdoctorid.getText()));

        setTreatment.setDate(txtdate.getText());

        setTreatment.setDetailTreatments(detailTreamentTableModel.getDetailtreatment());
        Double totalcost = setTreatment.calculateCost();
        setTreatment.setTotalCost(totalcost);

        if (setTreatment.getId() != null && setTreatment.getId() != 0) {
            try {
                treatmentController.save(setTreatment);

            } catch (Exception ex) {
                Logger.getLogger(addtreatment.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                treatmentController.save(setTreatment);
            } catch (Exception ex) {
                Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
            }
            // int ii=1;
            treatmentTablemodel.getTreatment().add(setTreatment);

            setFielNull();
            setNullFiel();
            detailTreamentTableModel.getDetailtreatment().clear();
            detailTreamentTableModel.fireTableDataChanged();
        }
        setEnableInputForm(inputform, false);
        treatmentTablemodel.fireTableDataChanged();

    }//GEN-LAST:event_btnsaveActionPerformed
    public void setNullFiel() {
        txtteethposition.setText("");
        txtcost.setText("");
        txttreatment.setText("");
    }
    private void btndeletetreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletetreatActionPerformed
        // TODO add your handling code here:
         int i=tableTreatmentDetail.getSelectedRow();
        DetailTreatment n=(DetailTreatment) detailTreamentTableModel.getDetailtreatment().get(i);
        try {
            if(n.getId()!=null){
            treatmentController.destroy(n.getId());
            }
            detailTreamentTableModel.getDetailtreatment().remove(i);
            detailTreamentTableModel.fireTableDataChanged();
        } catch (Exception ex){
        Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }
        setNullFiel();
    }//GEN-LAST:event_btndeletetreatActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        this.setEnableInputForm(true);
        java.util.Date date = new java.util.Date();
        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.LONG);

        String dateStr = dateFormat.format(date);
        txtdate.setText(dateStr);
        setTreatment = new Treatment();

    }//GEN-LAST:event_btnnewActionPerformed
/**/
   Treatment setTreatment;

    public void setFielNull() {
        txttreatmentid.setText("");
        txtcustomerid.setText("");
        txtdoctorid.setText("");
        txtdate.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtreat;
    private javax.swing.JButton btncancle;
    private javax.swing.JButton btndeletetreat;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel inputform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTreament;
    private javax.swing.JTable tableTreatmentDetail;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdoctorid;
    private javax.swing.JTextField txtteethposition;
    private javax.swing.JTextField txttreatment;
    private javax.swing.JTextField txttreatmentid;
    // End of variables declaration//GEN-END:variables
}



