/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newclinicprojec.Jpanel;

import java.awt.Component;
import java.sql.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.AbstractButton;
import javax.swing.table.AbstractTableModel;
import newclinicprojec.controllers.CustomerJpaController;
import newclinicprojec.controllers.DetailTreatmentJpaController;
import newclinicprojec.controllers.exceptions.NonexistentEntityException;
import newclinicprojec.entities.Customer;

/**
 *
 * @author Johm_93
 */
public class customerdata extends javax.swing.JPanel {

    /**
     * Creates new form customerdata
     */
    public customerdata() {
        initComponents();

    }

    EntityManagerFactory emf;
    CustomerJpaController controller;
    CustomerTableModel customerTableModel;
    public customerdata(EntityManagerFactory emf) {
        this.emf = emf;
        initComponents();
       this.emf=Persistence.createEntityManagerFactory("NewClinicProjecPU");
        this.controller = new CustomerJpaController(this.emf);
        List<Customer> customer=this.controller.findCustomerEntities();
        this.customerTableModel=new CustomerTableModel(customer);
        tablecustomerdata.setModel(this.customerTableModel);
       this.setEnableCustomerdata(this.customerdata,false);
    }
    

     public void setEnableCustomerdata(javax.swing.JPanel p, boolean b) {

        for (Component c : p.getComponents()) {
            c.setEnabled(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        customerdata = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        txtbirthdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtdisease = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdrug = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btncancle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecustomerdata = new javax.swing.JTable();
        btnnew = new javax.swing.JButton();
        bntedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        jLabel1.setText("Customer Data");

        jLabel3.setText("Name");

        jLabel4.setText("Sex");

        jLabel5.setText("Birthdate");

        buttonGroup1.add(radioMale);
        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioFemale);
        radioFemale.setText("Female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });

        jLabel6.setText("Address");

        jLabel7.setText("Phone");

        jLabel8.setText("Disease");

        jLabel9.setText("Allgery Drug");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btncancle.setText("Cancle");
        btncancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancleActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Id");

        javax.swing.GroupLayout customerdataLayout = new javax.swing.GroupLayout(customerdata);
        customerdata.setLayout(customerdataLayout);
        customerdataLayout.setHorizontalGroup(
            customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdisease)
                    .addComponent(txtaddress)
                    .addComponent(txtbirthdate)
                    .addComponent(txtname)
                    .addGroup(customerdataLayout.createSequentialGroup()
                        .addComponent(radioMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioFemale)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtphone)
                    .addComponent(txtdrug, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(customerdataLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancle)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(customerdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcustomerid))
        );
        customerdataLayout.setVerticalGroup(
            customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioMale)
                    .addComponent(radioFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerdataLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerdataLayout.createSequentialGroup()
                        .addComponent(txtdisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(customerdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btncancle))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tablecustomerdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Sex", "Birthdate", "Address", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablecustomerdata);

        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        bntedit.setText("Edit");
        bntedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteditActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnnew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntedit)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnew)
                            .addComponent(bntedit)
                            .addComponent(btndelete))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //get set model
        String cust=txtcustomerid.getText();
        int cumid=Integer.parseInt(cust);
        currentCustomer.setCustomerid(cumid);
        currentCustomer.setName(txtname.getText());
        currentCustomer.setSex(gender);
        currentCustomer.setBirthdate(txtbirthdate.getText());
        currentCustomer.setAddress(txtaddress.getText());
        currentCustomer.setPhone(txtphone.getText());
        currentCustomer.setCongenital(txtdisease.getText());
        currentCustomer.setDrug(txtdrug.getText());
        if(currentCustomer.getId() != null&&currentCustomer.getId()!=0){
            try {
                controller.edit(currentCustomer);
                customerTableModel.fireTableDataChanged();
            } catch (Exception ex) {
                Logger.getLogger(customerdata.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            controller.create(currentCustomer);
           // int ii=1;
           customerTableModel.customer.add(currentCustomer);
            customerTableModel.fireTableDataChanged();
        }
        setNullFiel();
        this.setEnableCustomerdata(customerdata,false);
    }//GEN-LAST:event_jButton1ActionPerformed

    Customer currentCustomer;
    
    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        currentCustomer = new Customer();
        this.setEnableCustomerdata(customerdata,true);
   
    }//GEN-LAST:event_btnnewActionPerformed
 public void setNullFiel(){
          txtcustomerid.setText("");
        txtname.setText("");
        buttonGroup1.clearSelection();
        txtbirthdate.setText("");
        txtaddress.setText("");
        txtdisease.setText("");
        txtdrug.setText("");
        txtphone.setText("");
 }
         
    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed

        gender="Female";// TODO add your handling code here:
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void bnteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteditActionPerformed
        // TODO add your handling code here:
        int i=tablecustomerdata.getSelectedRow();
       // System.out.println("HELLO");
        Customer customer = customerTableModel.customer.get(i);
        String cusid=customer.getCustomerid().toString();
        String sex=customer.getSex();
        txtcustomerid.setText(cusid);
        txtname.setText(customer.getName());
        if(sex=="Male")
            gender="Male";
        else
            gender="Female";
        Enumeration buttons = buttonGroup1.getElements();
        while(buttons.hasMoreElements()){
            AbstractButton btn = (AbstractButton)buttons.nextElement();
            if (btn.getActionCommand().equalsIgnoreCase(sex)){
                btn.setSelected(true);
            }
        }
        
        
        txtbirthdate.setText(customer.getBirthdate());
        txtaddress.setText(customer.getAddress());
        txtphone.setText(customer.getPhone());
        txtdisease.setText(customer.getCongenital());
        txtdrug.setText(customer.getDrug());
        List<Customer> customers=customerTableModel.getCustomer();
        setEnableCustomerdata(customerdata, true);
        txtcustomerid.setEnabled(false);
        currentCustomer=customer;
       
    }//GEN-LAST:event_bnteditActionPerformed

    private void btncancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleActionPerformed
        // TODO add your handling code here:
        setEnableCustomerdata(customerdata, false);
        setNullFiel();
    }//GEN-LAST:event_btncancleActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i=tablecustomerdata.getSelectedRow();
        Customer n=(Customer) customerTableModel.customer.get(i);
        
        try {
            controller.destroy(n.getId());
            customerTableModel.customer.remove(i);
            customerTableModel.fireTableDataChanged();
        } catch (Exception ex){
        Logger.getLogger(customerdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntedit;
    private javax.swing.JButton btncancle;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel customerdata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tablecustomerdata;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbirthdate;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtdisease;
    private javax.swing.JTextField txtdrug;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
private String gender=null;

}
class CustomerTableModel extends AbstractTableModel{
        String[] columName={"CustomeId","Name","Sex","Birthdate","Address","Phone","CongenitalDisease","AllgeryDrug"};
        List<Customer> customer;

    public CustomerTableModel(List<Customer> customers) {
        this.customer=customers;
        this.fireTableDataChanged();//To change body of generated methods, choose Tools | Templates.
    }

        public List<Customer> getCustomer() {
            return customer;
        }

        public void setCustomer(List<Customer> customer) {
            this.customer = customer;
            this.fireTableDataChanged();
        }
        public String[] getColumName() {
            return columName;
        }

        public void setColumName(String[] columName) {
            this.columName = columName;
        }
    @Override
    public int getRowCount() {
        return customer.size(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getColumnCount() {
        return columName.length; //To change body of generated methods, choose Tools | Templates.
    }

     @Override
    public String getColumnName(int i) {
        return columName[i];
    }
    @Override
    public Object getValueAt(int i, int i1) {
        Customer cust=customer.get(i);
        switch(i1){
            case 0:
                return cust.getCustomerid();
            case 1:
                return cust.getName();
            case 2:
                return cust.getSex();
            case 3:
                return cust.getBirthdate();
            case 4:
                return cust.getAddress();
            case 5:
                return cust.getPhone();
            case 6:
                return cust.getCongenital();
            case 7:
                return cust.getDrug();
            default:
                return null;
        }
        //To change body of generated methods, choose Tools | Templates.
    }
    }
